name: Spring demo GHA

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs :
  build :
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: action/checkout@v3

      - name: Setup JDK
      - uses: actions/setup-java@v3